### ISSUE TITLE
Add yaml config properties for Duo.com 2FA

### ISSUE THREAD

**Issue by carte7000** [ecadlabs/auth#15]
The duo.com API requires the following properties to authenticate an application

- Integration key
- Secret key
- API hostname

You can learn more about them here: https://duo.com/docs/authapi-guide

We would like to add it to our current config.yaml file under a property called duo_2fa
The schema could look like this

```
duo_2fa:
    integration_key: <INTEGRATION_KEY>
    secret_key: <SECRET_KEY>
    api_hostname: <API_HOSTNAME>
```

We might want to allow storing the secret using HashiCorp Vault when #7 is ready
